version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/var/log/appsec
    environment:
      TREND_AP_KEY: ${APPSEC_KEY}
      TREND_AP_SECRET: ${APPSEC_SECRET}
      CONNECTION_STRING: Server=mysql;Database=test_app_dotnetcore;User=root;Password=;
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: test_app_dotnetcore